### ISSUE TITLE
Can't install : pm ! Error: Tag stable not found for package tweetstream

### ISSUE THREAD

**Issue by ghost** [mikeal/tweetstream#1]
```
$ sudo   npm install tweetstream
The "ini" module will be removed in future versions of Node, please extract it into your own code.
npm configfile /Users/julien/.npmrc
npm sudo true
npm cli [ 'install', 'tweetstream' ]
npm install pkg tweetstream
npm fetch data tweetstream
npm GET tweetstream
npm install pkg tweetstream

npm ! Error: Tag stable not found for package tweetstream
    at F (/Users/julien/.node_libraries/.npm/npm/0.1.13/package/lib/install.js:136:19)
    at /Users/julien/.node_libraries/.npm/npm/0.1.13/package/lib/install.js:128:16
    at IncomingMessage.<anonymous> (/Users/julien/.node_libraries/.npm/npm/0.1.13/package/lib/utils/registry.js:149:7)
    at IncomingMessage.emit (events:42:20)
    at HTTPParser.onMessageComplete (http:110:23)
    at Client.ondata (http:859:22)
    at IOWatcher.callback (net:373:31)
    at node.js:204:9

npm failure try running: 'npm help install'
npm failure Report this *entire* log at <http://github.com/isaacs/npm/issues>
npm failure or email it to <npm-@googlegroups.com>
```

Maybe something that I'm missing out?

**Comment by mikeal** [comment]
sorry it took me so long to fix this, i've been at conferences all week.

i pushed a "stable" tag on 0.2.0
