### ISSUE TITLE
stream.end() throws error

### ISSUE THREAD

**Issue by polotek** [mikeal/tweetstream#2]
/Users/polotek/.node_libraries/.npm/tweetstream/0.2.0/package/lib/main.js:86
    client.end();
    ^
ReferenceError: client is not defined
    at EventEmitter.<anonymous> (/Users/polotek/.node_libraries/.npm/tweetstream/0.2.0/package/lib/main.js:86:5)
    at EventEmitter.emit (events:25:26)
    at EventEmitter.end (/Users/polotek/.node_libraries/.npm/tweetstream/0.2.0/package/lib/main.js:83:36)
    at Timer.callback (/Users/polotek/www/node/tweetstream.js:26:12)
    at node.js:255:9

**Comment by mikeal** [comment]
Good find.

Fixed in 7f4d925
